version: '3.8'
services:
  codinvpy:
    container_name: codinvpy
    image: ghcr.io/codinv/codinvpy
    network_mode: bridge
    volumes:
      - ./:/app
    environment:
      - TZ=Europe/Moscow
      - PY_SCRIPT=./startup_script.py
    restart: unless-stopped